Issue #104: Design preamble-detector
knezicm/pds-2022 pull request #109
Opened 2022-12-09 13:27 UTC by Jovann2424

- Added entity definition for the design
- Added initial code for architecture
- Created an initial testbench code for the design
- Added documentation with doxygen tool

2022-12-10 14:44 UTC, knezicm requested changes

2022-12-10 14:44 UTC, knezicm commented on assignments/104/preamble_detector.vhd
> +-- !@brief Description of this entity
Ovdje treba da se nalazi stvarni kratki i detaljni opis entiteta dizajna, a ne generički komentar koji ništa ne znači. Inače, kakva je poenta dokumentovanja dizajna?

2022-12-10 14:44 UTC, knezicm commented on assignments/104/preamble_detector.vhd
> +  rst_i   : in  std_logic;  -- !Reset enable when '1' or disable
Šta znači "or disable"?

2022-12-10 14:44 UTC, knezicm commented on assignments/104/preamble_detector.vhd
> +  data_i  : in  std_logic;  -- !Input data
Detaljnije opisati značenje ulaznog i izlaznog porta (šta predstavlja, tj. kakav podatak),

2022-12-10 14:44 UTC, knezicm commented on assignments/104/preamble_detector.vhd
> +-- !@details More details about this element.
Isto kao iznad. Generički opis arhitekture nije prihvatljiv.

2022-12-10 14:44 UTC, knezicm commented on assignments/104/preamble_detector_vhd_tst.vhd
> +-- Copyright (C) 2022  Intel Corporation. All rights reserved.
Zaglavlje nije u skladu sa propisanim. Ako ste koristili alate za automatsko generisanje testbench-a, i dalje morate prilagoditi zaglavlje kako smo definisali u coding style-u. Takođe, naziv TB fajla nije u skladu sa instrukcijama (pogledajte još jednom prethodni zadatak).

2022-12-10 14:48 UTC, knezicm requested changes

2022-12-10 14:48 UTC, knezicm commented on assignments/104/preamble_detector.vhd
> +-----------------------------------------------------------------------------
Nedostaje odrednica dokumentacije koja se odnosi na ime fajla. Pogledajte doxygen primjer.

2022-12-11 10:24 UTC, knezicm requested changes

2022-12-11 10:24 UTC, knezicm commented on assignments/104/preamble_detector.vhd
> +-----------------------------------------------------------------------------
Ovo i dalje nedostaje.

2022-12-11 10:24 UTC, knezicm commented on assignments/104/preamble_detector.vhd
> +-- !Use standard library
Doxygen parvila definisu da komentar mora da pocinje sa `--!`, a ne sa `-- !`, inace se dokumentacija nece ispravno generisati. Istina, ovo ce dovesti do toga da Vam ne prolazi linter faza worflow provjere, ali to mozete slobodno ignorisati.

2022-12-11 10:24 UTC, knezicm commented on assignments/104/preamble_detector.vhd
> +-- !@brief In digital communications, a synchronization bit sequence known as
Ovo vise spada pod `@details` umjesto pod `@brief`. Segment `@brief` je maksimalno jedna recenica.

2022-12-11 10:24 UTC, knezicm commented on assignments/104/preamble_detector.vhd
> +-- !@details More details about this element.
Opet genericki komentar.

2022-12-11 10:24 UTC, knezicm commented on assignments/104/preamble_detector.vhd
> +  rst_i   : in  std_logic;  -- !Reset signal: When the input signal is '1' then
"Force circuit to go into reset state" je sasvim dovoljan komentar.

2022-12-11 10:24 UTC, knezicm commented on assignments/104/preamble_detector.vhd
> +  data_i  : in  std_logic;  -- !Input data: Each clock signal is followed
Ne ocekujem da dokumetujete ponasanje, vec znacenje signala/porta. Npr. "This port receives input data for which preamble is detected"

2022-12-11 10:24 UTC, knezicm commented on assignments/104/preamble_detector.vhd
> +  match_o : out std_logic   -- !Output data: When the sequence appears at the output,
High for one clock period when preamble is detected.

2022-12-11 10:24 UTC, knezicm commented on assignments/104/preamble_detector.vhd
> +-- !@brief Architecture definition of the preamble_detector: a state machine that
Opet, mijesate _brief_ i _details_.

2022-12-13 10:51 UTC, knezicm approved these changes

2022-12-13 10:51 UTC, knezicm commented on assignments/104/preamble_detector.vhd
> +--! State register--
Imas na par mjesta ovo `--` nakon komentara. Izbaci to i mozemo da merge-amo.

2022-12-13 12:59 UTC, Jovann2424 commented on assignments/104/preamble_detector.vhd
> +--! State register--
Mislim da sam sada uklonio sve gdje su bili takvi komentari.

2022-12-13 18:22 UTC, milos991 approved these changes

2022-12-13 18:31 UTC, merged