Issue #103 : Create preamble generator
knezicm/pds-2022 pull request #110
Opened 2022-12-10 13:53 UTC by Nemanja0

- Added entity for design
- Added tesbench file for preamble generator entity

2022-12-10 14:11 UTC, Nemanja0 commented
Javlja mi gresku [Comments] space required after comment kod --! komentara. Ukoliko napisem u obliku -- !, onda prolazi, medjutim doxygen ih vidi kao obicne komentare a ne kao --!. Ako moze samo pomoc oko toga da mi ne ispisuje tu gresku.

2022-12-11 10:14 UTC, knezicm commented
Slobodno ignorišite zahtjev lintera koji je vezan za Doxygen komentare. To je izuzetak od pravila nametnutog code style pravilima. Dakle, forsirajte doxygen pravila bez obzira što će da padne workflow u linter segmentu.

Međutim, koliko vidim, Vama ne prolazi verifikacija dizajna, a to morate popraviti.

2022-12-11 10:29 UTC, knezicm requested changes
Popravite greske koje dobijate pri verifikaciji dizajna.

2022-12-11 10:29 UTC, knezicm commented on assignments/103/preamble_generator.vhd
> +    clk_i   : in  std_logic; --! input clock signal
Sve recenice treba da pocinju velikim slovom, dakle "Input clock signal."

2022-12-11 12:00 UTC, Nemanja0 commented
Nije mi jasno zašto ne prolazi verifikacija dizajna. Probao sam izmjeniti neke stvari, ali opet isto. Kada pokrenem simulaciju dizajn se ponaša u skladu sa zahtjevima.

2022-12-11 12:16 UTC, knezicm commented
Uvijek postoji šansa da drugačije razumijemo specifikacije. U tome i jeste čar verifikacije. Uključiću @milos991 u diskusiju, čisto ako postoje neke nedoumice. Međutim, iz logova mi se čini da je problem u invertovanoj logici.

![image](https://user-images.githubusercontent.com/28368588/206902900-998b7c08-310e-4721-9317-00d20d1218f3.png)

Kao što vidite iz slike iznad, očekuje se da signal bude postavljen na LOW, kod Vas je HIGH. Slično, kod Vas je preambula 0x55, a očekivano je da bude 0xaa. Možda je prosto stvar u interpretaciji _little-endian_/_big-endian_ notacije i aktivnom logičkom nivou kontrolnog signala.

2022-12-11 12:18 UTC, knezicm commented
Takođe, može biti da Vam je signal nekako pomjeren, tj. zakašnjen u odnosu na očekivano stanje.

2022-12-11 12:40 UTC, Nemanja0 commented
Pokušao sam invertovati signal na izlazu i opet isto.

![simluacija](https://user-images.githubusercontent.com/59769533/206903992-35adf4fe-5abe-4b59-8617-b10607259e14.png)
Ovo je slika simulacije kada izlaz nije invertovan i vidi se kada se start_i postavi na 1 da se na izlazu pojavi 10101010. Prvi signal na slici je klok signal, drugi reset, treći start i četvrti izlazni signal.

2022-12-12 10:23 UTC, milos991 commented
Promijenite da aktivna ivica takta bude rastuca, a ne opadajuca, jer testno okruzenje ocekuje rastucu ivicu, pa probajte ponovo pustiti simulaciju.

2022-12-12 10:49 UTC, Nemanja0 commented
Prvobitno sam radio sa rastucom ivicom. Kasnije sam probao i sa opadajucom, za svaki slucaj. Predlazem da probam uraditi koristenjem neke druge metodologije koja nije look-ahead.

2022-12-12 11:01 UTC, knezicm commented
Nemam nista protiv, ali ako racionalizujete zasto je _look-ahead_ metodologija u ovom slucaju problematicna.

2022-12-13 18:33 UTC, milos991 commented
Imate problem sa design-om u slucaju kada je start_i port postavljen na '1' duze od jednog takt ciklusa, izlaz treba da bude u idle stanju, a kod vas nije taj slucaj (slika 1).

![103s1](https://user-images.githubusercontent.com/91080479/207416335-933bccd4-140f-4d92-a1c4-20ca717969ca.png)


Plus kada se "spusti" start_i na '0', potrebno je da se preambula generise u narednih 8 ciklusa, sto opet nije slucaj (slika 2).
![103s2](https://user-images.githubusercontent.com/91080479/207416393-9bd6a23f-71ed-4b5d-89f6-19e2134b7429.png)

2022-12-14 11:36 UTC, knezicm approved these changes

2022-12-17 13:34 UTC, merged