Created NRZI decoder
knezicm/pds-2022 pull request #111
Opened 2022-12-11 12:41 UTC by Cetic99

Created testbench
Tested
Written doxygen comments
Formated

2022-12-11 12:50 UTC, Cetic99 commented
Не разумијем грешку код верификације. Ако вам није проблем да ми појасните.

2022-12-11 13:38 UTC, knezicm commented
Odgovor je zapravo vrlo jednostavan. Za zadatak koji radite, jos uvijek nije pripremljen odgovarajuci test. Kada bude pripremljen, manuelno cemo da pokrenemo provjeru. Do tada, ostaje samo da cekate (eventualno popravljate greske za code style ako ih ima).

2022-12-12 10:50 UTC, milos991 commented
Do kraja dana cu da postavim test.

2022-12-13 10:48 UTC, knezicm requested changes

2022-12-13 10:48 UTC, knezicm commented on assignments/107/nrzi_decoder.vhd
> +--! \file nrzi_decoder_tb.vhd
Ovo treba da ide poslije zaglavlja. Dakle, prvo zaglavlje, pa onda doxygen komentari.

2022-12-13 10:48 UTC, knezicm commented on assignments/107/nrzi_decoder.vhd
> +--! Entity is created using Moore FSM with 4 states.
Stavi ovo kao `@details`.

2022-12-13 10:48 UTC, knezicm commented on assignments/107/nrzi_decoder.vhd
> +architecture arch of nrzi_decoder is
Dodati dokumentaciju za arhitekturu.

2022-12-13 10:48 UTC, knezicm commented on assignments/107/nrzi_decoder_tb.vhd
> +--! \file nrzi_decoder_tb.vhd
Testbench fajl se ne dokumentuje, izbaciti sve doxygen komentare da se linter ne zali.

2022-12-13 12:03 UTC, knezicm requested changes

2022-12-13 12:03 UTC, knezicm commented on assignments/107/nrzi_decoder.vhd
> +entity nrzi_decoder is
Igramo se ping-ponga. Dakle, sada nedostaje dokumentacija za entitet. Morate da dokumentujete entitet i arhitekturu. Oba segmenta moraju da imaju brief i details. Brief je obavezan, a ovdje to nedostaje i kod arhitekture.

2022-12-13 18:24 UTC, milos991 approved these changes

2022-12-17 13:35 UTC, knezicm approved these changes

2022-12-17 13:35 UTC, merged