Issue #106 : Nrzi encoding circuit
knezicm/pds-2022 pull request #130
Opened 2022-12-22 21:34 UTC by jovanabozic

- Issue #106 : Create NRZI encoding circuit 
-Adding entity nrzi_encoder
-Adding testbench nrzi_encoder_tb

2022-12-23 10:54 UTC, milos991 approved these changes

2022-12-23 19:56 UTC, knezicm requested changes

2022-12-23 19:56 UTC, knezicm commented on assignments/106/nrzi_encoder.vhd
> +-- !@file
Komentari koji se odnose na doxygen treba da pocinju sa  `--!`, a ne `-- !`. Linter ce prijaviti gresku ali to je izuzetak koji tolerisemo. Molim Vas da izmijenite opis dizajna tako da komentari budu u skladu sa doxygen pravilima, inace se dokumentacija nece ispravno generisati.

2022-12-23 19:56 UTC, knezicm commented on assignments/106/nrzi_encoder.vhd
> +-- unit name:    MULTI_FUNCTION_ARITMETIC_UNIT
Promijeniti u skladu sa nazivom dizajna.

2022-12-23 19:56 UTC, knezicm commented on assignments/106/nrzi_encoder.vhd
> +--   This file describe circuit that can do following operation: +, -, +1, -1 .
Promijeniti u skladu sa dizajnom.

2022-12-23 19:56 UTC, knezicm commented on assignments/106/nrzi_encoder.vhd
> +-- !@details This entity represent Non return to zero Inverted encoder of input signal.
Dokumentovati strukturu entiteta, tj. napisati da sadrzi ulaze za takt i reset, te ulayni signal koji se koduje i izlazni kodovani signal.

2022-12-23 19:56 UTC, knezicm commented on assignments/106/nrzi_encoder_tb.vhd
> +-- unit name:     MULTI_FUNCTION_ARITMETIC_UNIT_TB
Azurirati.

2022-12-23 19:56 UTC, knezicm commented on assignments/106/nrzi_encoder_tb.vhd
> +--   This file represent testbench  of MULTI_FUNCTION_ARITMETIC_UNIT circuit.
Azurirati.

2022-12-23 19:56 UTC, knezicm commented on assignments/106/nrzi_encoder_tb.vhd
> +-------------------------------------------------------
Testbench se ne dokumentuje. Prema tome, izbaciti sve doxygen komentare iz TB fajla.

2022-12-26 11:44 UTC, jovanabozic commented on assignments/106/nrzi_encoder_tb.vhd
> +-------------------------------------------------------
@knezicm 

Postovani profesore , sto se tice doxygen alata, uspjesno sam ga instalirala na laptop, tako da sam probala generisati dokumentaciju, i znala sam da "--" i  "!" moraju da se pisu spojeno, medjutim zbunilo me je to sto 
u provjeri stila pisanja mora da se napravi razmak poslije "--". 
Uglavnom, ispravila sam sve greske.

2022-12-26 13:24 UTC, knezicm approved these changes

2022-12-26 13:24 UTC, merged