Issue #102: Create dual-edge detector circuit using Mealy fsm
knezicm/pds-2022 pull request #138
Opened 2022-12-30 10:55 UTC by ElezovicA

- Added entity definition for the design
- Added initial code for architecture
- Created an initial testbench code for the design

2022-12-30 12:28 UTC, ElezovicA commented
Pozdrav.
[dual_edge_detector.txt](https://github.com/knezicm/pds-2022/files/10324671/dual_edge_detector.txt)
Iz nekog razloga ne uspjevam prebaciti VHDL fajl, testbench je prošao bez problema, ali vhdl ne prepoznaje.

2022-12-30 17:30 UTC, ElezovicA commented
Do mene je, uspjela sam sad.

2023-01-10 08:51 UTC, milos991 commented
> @milos991 Poštovanje, uvidjela sam grešku, da li je u redu da izmjene predam sutra u toku dana?

Naravno.

2023-01-11 20:13 UTC, ElezovicA commented
@milos991 
Poštovani, možete li pogledati da li je sada u redu pošto mi lokalno prolazi sve kako reba ali ovdje ne?

2023-01-12 13:05 UTC, milos991 commented
Kao sto mozete vidjeti sa talasnih oblika, vas design detektuje samo jednu ivicu, trebao bi obje.

![image](https://user-images.githubusercontent.com/91080479/212073866-17e06a7f-f18c-4f62-8c07-75f5a9e6f31b.png)

2023-01-12 20:43 UTC, ElezovicA commented
> Kao sto mozete vidjeti sa talasnih oblika, vas design detektuje samo jednu ivicu, trebao bi obje.
> 
> ![image](https://user-images.githubusercontent.com/91080479/212073866-17e06a7f-f18c-4f62-8c07-75f5a9e6f31b.png)

Ali kada pokušam da detektuje obje ivice onda mi izbacuje grešku.
![Quartus Prime Lite Edition - C__Users_AMG_Computers_Desktop_Faks_PDS_dual_edge_detector - dual_edge_detector 1_12_2023 9_40_04 PM (2)](https://user-images.githubusercontent.com/116368163/212176763-6feab055-a03f-44f2-b3f4-25ca1335c1a9.png)

2023-01-12 20:51 UTC, knezicm commented
Osnovni principi sinhronog dizajna kazu da se vrijednost registra moze mijenjati na jednu aktivnu ivicu takta, a ne na obje (nemojte da brkate takt signal i ulazni signal cije ivice detektujete). Malo pazljivije pogledajte video materijale. O tome se prilicno govorilo tamo. Nakon toga, pokusajte da revidirate masinu stanja za detektor jedne ivice, tako da se detektuju obje. As simple aa that. :) Srecno!

2023-01-18 11:01 UTC, milos991 requested changes
Nema .sdc file-a i sinteza ne prolazi kako treba.

------------------------------------------------------------
Warning: : /home/mknezic/actions-runner/_work/pds-2022/pds-2022/pds-verif/verif/../../assignments/102/dual_edge_detector.sdc file does not exist!
------------------------------------------------------------

2023-01-18 11:45 UTC, ElezovicA commented
> Nema .sdc file-a i sinteza ne prolazi kako treba.
> 
> ## Warning: : /home/mknezic/actions-runner/_work/pds-2022/pds-2022/pds-verif/verif/../../assignments/102/dual_edge_detector.sdc file does not exist!

![Screenshot (2)](https://user-images.githubusercontent.com/116368163/213163338-fb8de554-d4a2-4459-b13e-ed6f7a0596eb.png)
Poštovani, u tekstu zadatka nije traženo da se dostavi .sdc fajl.

2023-01-18 12:57 UTC, milos991 commented
> > Nema .sdc file-a i sinteza ne prolazi kako treba.
> > 
> > ## Warning: : /home/mknezic/actions-runner/_work/pds-2022/pds-2022/pds-verif/verif/../../assignments/102/dual_edge_detector.sdc file does not exist!
> 
> ![Screenshot (2)](https://user-images.githubusercontent.com/116368163/213163338-fb8de554-d4a2-4459-b13e-ed6f7a0596eb.png)
> Poštovani, u tekstu zadatka nije traženo da se dostavi .sdc fajl.

 Izvinjavam se, moja greška. :)

2023-01-18 13:17 UTC, milos991 approved these changes

2023-01-18 13:47 UTC, ElezovicA commented
> Svi VHDL fajlovi, ukljucujuci i testbench, moraju da imaju ekstenziju `.vhd`. Kada izmijenite ekstenziju za testbench fajl, vidjecete da imate greske vezane za coding style koje je potrebno ispraviti.



> Svi VHDL fajlovi, ukljucujuci i testbench, moraju da imaju ekstenziju `.vhd`. Kada izmijenite ekstenziju za testbench fajl, vidjecete da imate greske vezane za coding style koje je potrebno ispraviti.



> Svi VHDL fajlovi, ukljucujuci i testbench, moraju da imaju ekstenziju `.vhd`. Kada izmijenite ekstenziju za testbench fajl, vidjecete da imate greske vezane za coding style koje je potrebno ispraviti.

Poštovanje, izvinjavam se, nisam primjetila da mi je fajl sa pogrešnom ekstenzijom. Prepravila sam sve.

2023-01-18 16:57 UTC, knezicm approved these changes

2023-01-18 16:58 UTC, merged