Issue #125: Create Binary-to-BCD conversion circuit
knezicm/pds-2022 pull request #139
Opened 2022-12-30 13:28 UTC by Jovann2424

Added entity for designed
Added initial code for architecture
Added binary_to_bcd.sdc file

2023-01-13 14:59 UTC, ElezovicA commented
Dizajn je jednostavan za razumijevanje, u skladu sa zahtjevima zadatka i prilikom pokretanja simulacije, lokalno, dobijeni su očekivani rezultati. Vremenska analiza sa dostavljenim .sdc fajlom prolazi bez greške. Pohvale za kolegu.

2023-01-13 15:01 UTC, ElezovicA approved these changes

2023-01-18 09:36 UTC, knezicm commented
Coding style nije zadovoljen, pa linter faza ne prolazi. Prema logovima, imate i greske koje ne potpadaju pod izuzetke vezane za Doxygen dokumentaciju.

2023-01-18 10:58 UTC, milos991 requested changes
Ne prolazi sinteza kako treba.

-------------------------------------------------------------------------
Critical Warning (332148): Timing requirements not met
Info (332146): Worst-case setup slack is -12.451
-------------------------------------------------------------------------

2023-01-18 14:33 UTC, ElezovicA commented
> Coding style nije zadovoljen, pa linter faza ne prolazi. Prema logovima, imate i greske koje ne potpadaju pod izuzetke vezane za Doxygen dokumentaciju.

Poštovanje, taj dan je bio rok za predaju pa nisam stigla ispraviti te greške. Dodala sam prepravljen fajl za testbench u kom su bile greške.

2023-01-18 17:00 UTC, knezicm commented
@Jovann2424 Ispravite ovo sto je @milos991 komentarisao da mozemo da merge-amo ovaj PR.

2023-01-18 17:10 UTC, Jovann2424 commented
U toku večeri ću raditi na tome da što prije ispravim sve.

2023-01-18 18:09 UTC, Jovann2424 commented
@knezicm Ispravio sam sve. Bilo je do perioda.

2023-01-18 21:06 UTC, knezicm approved these changes

2023-01-23 09:43 UTC, merged