Issue #49: Create four-bit comparator
knezicm/pds-2022 pull request #59
Opened 2022-11-09 16:25 UTC by Jovann2424

- Added initial code for architecture
- Added entity definition for the design of two-bit comparator
- Added initial code for architecture using structural description"

2022-11-10 10:49 UTC, milos991 requested changes
Kompajliranje nije uspjesno, nalijepicu compile log ispod vidite u cemu je problem da mozete ispraviti.

--------------------------------------------------------------------------------------------------------
vcom -work issue_49_lib -2008 -source -check_synthesis "+cover=sbcef" -fsmverbose -f issue49.filelist -l 49/test_results/log_files/vcom.log 
-- Loading package STANDARD
-- Loading package TEXTIO
-- Loading package std_logic_1164
-- Loading package std_logic_arith
-- Loading package STD_LOGIC_UNSIGNED
-- Compiling entity four_bit_comparator
-- Compiling architecture arch_four_bit_comparator of four_bit_comparator
###### /home/mknezic/actions-runner/_work/pds-2022/pds-2022//assignments/49/four_bit_comparator.vhd(31): 		port map (A(0) => i_A(0), A(1) => i_A(1), B(0) => i_A(2), B(1) => i_A(3), AEQB => equal1, AGTB => greater1, ALTB => less1);
** Error: /home/mknezic/actions-runner/_work/pds-2022/pds-2022//assignments/49/four_bit_comparator.vhd(31): (vcom-1193) Formal "A" length is 3; number of individual associations is 2.
** Error: /home/mknezic/actions-runner/_work/pds-2022/pds-2022//assignments/49/four_bit_comparator.vhd(31): (vcom-1193) Formal "B" length is 3; number of individual associations is 2.
###### /home/mknezic/actions-runner/_work/pds-2022/pds-2022//assignments/49/four_bit_comparator.vhd(34): 		port map (A(0) => i_B(0), A(1) => i_B(1), B(0) => i_B(2), B(1) => i_B(3), AEQB => equal2, AGTB => greater2, ALTB => less2);
** Error: /home/mknezic/actions-runner/_work/pds-2022/pds-2022//assignments/49/four_bit_comparator.vhd(34): (vcom-1193) Formal "A" length is 3; number of individual associations is 2.
** Error: /home/mknezic/actions-runner/_work/pds-2022/pds-2022//assignments/49/four_bit_comparator.vhd(34): (vcom-1193) Formal "B" length is 3; number of individual associations is 2.
###### /home/mknezic/actions-runner/_work/pds-2022/pds-2022//assignments/49/four_bit_comparator.vhd(42): end arch_four_bit_comparator;
** Error: /home/mknezic/actions-runner/_work/pds-2022/pds-2022//assignments/49/four_bit_comparator.vhd(42): VHDL Compiler exiting
End time: [17](https://github.com/knezicm/pds-2022/actions/runs/3429667100/jobs/5715593641#step:6:18):26:02 on Nov 09,[20](https://github.com/knezicm/pds-2022/actions/runs/3429667100/jobs/5715593641#step:6:21)[22](https://github.com/knezicm/pds-2022/actions/runs/3429667100/jobs/5715593641#step:6:23), Elapsed time: 0:00:00
Errors: 5, Warnings: 0
--------------------------------------------------------------------------------------------------------

2022-11-11 12:59 UTC, Jovann2424 commented
Ispravio sam greške

2022-11-13 16:45 UTC, milos991 approved these changes

2022-11-14 08:26 UTC, knezicm approved these changes

2022-11-14 08:26 UTC, merged