Issue #51: Design 2-4 decoder with enable input (first method) - Adde…
knezicm/pds-2022 pull request #63
Opened 2022-11-13 12:21 UTC by ElezovicA

2022-11-13 17:43 UTC, milos991 requested changes
Postovana, compile ne prolazi. Nalijepicu Vam compile-log ispod da mozete vidjeti sta nije u redu pa da shodno tome unesete izmjene. Zbog malih tehnickih problema to jos nije vidljivo u "check" tab-u, ali bice uskoro i to popravljeno, Hvala na razumijevanju.

************************************************************************************************************
###### /home/milos/workspace/etf/classes/pds/pds-2022-v2/pds-2022//assignments/51/decoder_2_4.vhd(18): case i_A is
** Error: /home/milos/workspace/etf/classes/pds/pds-2022-v2/pds-2022//assignments/51/decoder_2_4.vhd(18): (vcom-1339) Case statement choices cover only 4 out of 81 cases.
###### /home/milos/workspace/etf/classes/pds/pds-2022-v2/pds-2022//assignments/51/decoder_2_4.vhd(26): end bhv;
** Error: /home/milos/workspace/etf/classes/pds/pds-2022-v2/pds-2022//assignments/51/decoder_2_4.vhd(26): VHDL Compiler exiting
************************************************************************************************************

2022-11-14 08:24 UTC, ElezovicA commented
Poštovanje,
Da li ovo znači da sam koristila pogrešan metod za rješavanje zadatka? Jer mi nije baš jasno u čemu je greška.

2022-11-14 17:39 UTC, knezicm commented
> Ja stvarno ne znam kako da prepravim kod pošto mi ne izbacuje u čemu je tačno greška. Pokušala sam realizovati dekoder na različite načine ali ne prolazi.

Vas PR ne prolazi iz drugih razloga (za odredjene PR testovi ne prolaze i trenutno rjesavamo ovaj problem). Sacekajte da @milos991 pokrene testove lokalno kod sebe i da ostavi komentar da li je sve u redu.

2022-11-15 12:11 UTC, milos991 approved these changes
Pustio sam kod sebe simulaciju i sada sve prolazi. Ako zelite vidjeti log-ove, javite mi se na mail (milos.kovacevic@etf.unibl.org) pa Vam mogu poslati .zip.

2022-11-15 16:20 UTC, knezicm approved these changes

2022-11-15 18:15 UTC, knezicm approved these changes

2022-11-15 18:15 UTC, merged