Issue #79: Design eight-bit multiplier
knezicm/pds-2022 pull request #93
Opened 2022-11-28 19:29 UTC by Jovann2424

Added entity definition for the design
Added initial code for architecture
Created an initial testbench code for the design

2022-11-28 19:35 UTC, Jovann2424 commented
Ja sam ovdje ovako postavio neki vid rješenja koje ne radi. Pošto vrijeme za predaju prolazi, a meni ne radi ni .vhd fajl, pa tako ne mogu ni preći na izradu testbench fajla, molim Vas možete li pogledati ovaj kod kako bih pokušao ispraviti. Naime, prilikom kompajliranja greške se prvo svode na tipove podataka sa kojim radim, te kada se "izborim" sa tim onda dobijem sledeću grešku:

Error (10476): VHDL error at eight_bit_multiplier.vhd(69): type of identifier "B_i" does not agree with its usage as "natural" type

Nakon toga mi vrati grešku da ne poredim dobre vrijednosti i dalje ne znam naći rješenje ovog problema:

Error (10385): VHDL error at eight_bit_multiplier.vhd(71): index value 8 is outside the range (7 downto 0) of object "A_i"

U komentaru ću ostaviti i dio drugog koda koji se svodi opet na iste greške. Više nisam siguran ni da li sam implementova algoritam kako treba:

process ( B_i, A_i)
	
	variable PA : unsigned ((A_i'length + B_i'length - 1) downto 0);
	variable BA : unsigned ((A_i'length + B_i'length - 1) downto 0);

	begin
		
		PA := (others => '0');
		BA := to_unsigned (B_i, A_i'length + B_i'length);
		for i in 0 to A_i' length loop
			if ((A_i(i)) = '1') then
				PA := PA + BA;
			end if;
		BA := shift_left ( BA, 1);
		end loop;
		RES_o <= std_logic_vector(PA);
		
	end process;

2022-11-28 20:14 UTC, knezicm commented
Popravite bar code style ako nemate ideju kako da dođete do rješenja. VHDL je strong-typed jezik, dakle, ne možete implicitno prebacivati jedan tip podatka u drugi. Indeksi nizova su strogo definisani, a očigledno pokušavate da pristupite elementu van granica niza (greška je više nego jasno naznačena).

Teško je pomoći, jer ja, za početak, uopšte ne bih koristio `shift_left()`. Kao što sam već rekao, operacija šiftovanja se trivijalno implementira u VHDL jeziku. Takođe, nisam siguran koje linije su u pitanju, jer ste ovdje okačili jedan opis, drugi ste predali, a teško je stvari analizirati van konteksta.

2022-11-29 15:13 UTC, knezicm commented
Još jedna napomena, kada otvorite PR, mene i Miloša dodajete u sekciju _Reviewers_, a ne _Assignees_ (kao što može da se vidi na slici ispod).

![image](https://user-images.githubusercontent.com/28368588/204567399-9846c4b3-78b2-4241-915e-ac1a87983e0c.png)

2022-11-29 16:33 UTC, Jovann2424 commented
Mahinalno sam Vas dodao u assignees, tek sada vidim. Ispraviću dok još pokušam riješiti ovaj problem.

2022-12-16 20:10 UTC, Jovann2424 commented
Kada je u pitanju ovaj zadatak, poslednje šta sam uradio i gdje sam stao se ticalo toga da ne prolazi sinteza, tj "zaledi" na 11% i dalje ne ide, a ne izbacuje ni grešku. Gledajući po internetu shvatio sam da jedan od osnovnih problema može biti prevelik broj iteracija uzrokovan nekom od petlji koje koristim. Vi kada ste radili mašine stanja takođe ste pribjegavali izbjegavanju petlje i isto je u pitanju bio množač. Kada sam sada pogledao poslenji video gdje se objašnjava pipeline, zapravo sam shvatio da ste objasnili i metod za ovaj zadatak. Da li je legitimno da se sada poslužim tim algoritmom :)?

2022-12-17 13:30 UTC, knezicm commented
Naravno. Zato taj zadatak i nije toliko tezak, samo treba pazljivo pogledati video materijale. ;)

2022-12-21 09:39 UTC, knezicm requested changes

2022-12-21 09:39 UTC, knezicm commented on assignments/79/eight_bit_multiplier_tb.vhd
> +--   This file implements a simple multiplier between two 8-bit number.
Ovo je testbench a ne dizajn.

2022-12-21 09:39 UTC, knezicm commented on assignments/79/eight_bit_multiplier_tb.vhd
> +-- unit name:   eight_bit_multiplier
Pogresan naziv. Treba dodati _tb

2022-12-21 14:08 UTC, Jovann2424 commented on assignments/79/eight_bit_multiplier_tb.vhd
> +-- unit name:   eight_bit_multiplier
Kopiranje, najljepši izvor grešaka 🙂

2022-12-22 08:14 UTC, knezicm approved these changes

2022-12-23 10:52 UTC, milos991 approved these changes

2022-12-23 20:18 UTC, merged