Issue #74 : Design multi-function arithmetic circuit
knezicm/pds-2022 pull request #96
Opened 2022-11-30 22:27 UTC by jovanabozic

-Adding adder, substractor, incrementor, decrementor component for first architecture of designe
 -Adding sub component for second architecture of multi-fun. design 
-Adding test bench for designe. Testbench do not test all combination of input vectors , because it would overload my local maschine .

2022-12-01 16:51 UTC, jovanabozic commented
Postovanje profesore,

Nisam bila u mogucnosti da pokrenem skriptu za provjeru code style na desktopu (racunar stalno iskljucuje aplikaciju kad je pozovem). 
Tako da sam ispravku koda radila direktno na repozitorijumu (komitujuci izmjene).
Takodjer, linter ukazuje da postoji jos  par gresaka tipa (HT, Trailing spaces). Ali neke od njih nisam bila u mogucnosti da otklonim. 
Jednostavno, i ako ne postoji prazan prostor posle zadnjeg karatkera koda, i ako nigdje nije koristen tab, neke od gresaka su i dalje prisutne.

2022-12-01 21:26 UTC, knezicm commented
U vezi pucanja aplikacije, sličan problem je imala @LTamara1013. Pogledajte diskusiju ovdje:

https://github.com/knezicm/pds-2022/pull/94

Što se tiče trailing spaces, fokusirajte se na linije koje Vam linter prijavljuje. Trailing space nije dozvoljen nigdje, ne nužno na lokacijama na koje ukazujete. Vjerujte, mnogo puta mi se desilo da mislim da je alat pogriješio, ali, ipak, ja na kraju nisam bio u pravu. :)

2022-12-03 13:54 UTC, milos991 approved these changes

2022-12-04 10:55 UTC, knezicm requested changes

2022-12-04 10:55 UTC, knezicm commented on assignments/74/multi_function_aritmetic_unit.vhd
> +      a_i(0)  => A_i(0),
Zašto prosto ne koristite `a_i => A_i`, `b_i => B_i`, and `c_o => tmp1`? Vektori su iste veličine.

2022-12-04 10:55 UTC, knezicm commented on assignments/74/multi_function_aritmetic_unit.vhd
> +      a_i(0)  => A_i(0),
Isto kao iznad.

2022-12-04 10:55 UTC, knezicm commented on assignments/74/multi_function_aritmetic_unit.vhd
> +      a_i(0)  => A_i(0),
Isto kao iznad.

2022-12-04 10:55 UTC, knezicm commented on assignments/74/multi_function_aritmetic_unit.vhd
> +      a_i(0)  => A_i(0),
Isto kao iznad.

2022-12-04 10:55 UTC, knezicm commented on assignments/74/multi_function_aritmetic_unit.vhd
> +--      a_i(0)  => A_i(0),
Isto kao iznad.

2022-12-08 10:12 UTC, jovanabozic commented on assignments/74/multi_function_aritmetic_unit.vhd
> +      a_i(0)  => A_i(0),
Postovanje profesore,
Mapirala sam vektore na nacin na koji ste ukazali.

2022-12-08 13:41 UTC, knezicm commented on assignments/74/multi_function_aritmetic_unit.vhd
> +      a_i(0)  => A_i(0),
Da, ali sada opet imate greške zbog kojih ne prolazi verifikacija. Očigledno je neki problem u vidljivosti `B_i` identifikatora.

![image](https://user-images.githubusercontent.com/28368588/206460934-d8c36129-dc22-4369-ad42-2c07c9600470.png)

2022-12-14 18:57 UTC, jovanabozic commented on assignments/74/multi_function_aritmetic_unit.vhd
> +      a_i(0)  => A_i(0),
@knezicm
 Postovani profesore. Napravila sam gresku kod mapiranja. 
Sada prolazi i verifikaciju.

2022-12-17 13:32 UTC, knezicm approved these changes

2022-12-17 13:33 UTC, merged